name: DevSecOps - SAST/DAST

on:
  push:
  pull_request:

jobs:
  sast-phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer --version

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHPCS (SAST)
        run: |
          mkdir -p reports
          php vendor/bin/phpcs -p --standard=PSR12 . > reports/phpcs.txt || true

      - name: Upload PHPCS report
        uses: actions/upload-artifact@v4
        with:
          name: phpcs-report
          path: reports/phpcs.txt
  sast-sonarcube:
      - name: Analyse du code avec SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=aghiles76
            -Dsonar.projectKey=aghiles76_mini-projet-devsecops-site-notes
  dast-zap:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Start PHP server
        run: |
          php -S 127.0.0.1:8000 > /tmp/phpserver.log 2>&1 &
          sleep 2

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: http://127.0.0.1:8000
          fail_action: false
          artifact_name: zap-report
          allow_issue_writing: true

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_html.html
            report_md.md
            report_json.json

  deploy:
    runs-on: ubuntu-latest
    needs: [sast-phpcs, dast-zap]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Déclencher le déploiement sur Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK"
